apiVersion: networking.istio.io/v1beta1
kind: VirtualService
metadata:
  name: nginx-vs
  namespace: test-app
spec:
  # 改為引用全域 Gateway
  gateways:
  - istio-system/monitoring-gateway 
  # 修改為 nginx 專屬的子網域，避免搶奪 www 主站流量
  hosts:
  - nginx.jacky3.com 
  http:
  - route:
    - destination:
        host: nginx-service.test-app.svc.cluster.local
        port:
          number: 80
